server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_registration?createDatabaseIfNotExist=true
    username: postgres
    password: root22
    #driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
